services:
 frontend:
    container_name: frontend
    build: 
      context: ./horizon/
      dockerfile: Dockerfile
    volumes:
      - frontend-vol:/app
    ports:
      - "3000:3000"
    stdin_open: true  # Keep STDIN open even if not attached
    tty: true         # Allocate a pseudo-TTY
    command: /bin/bash  # Replace with /bin/sh if bash is not available

volumes:
  frontend-vol:
    driver: local
    driver_opts:
      o: bind
      type: 'none'
      device: ${PWD}/horizon


# Docker commands to use
# docker compose -f ./docker-compose.yml  up -d --build
# docker compose -f ./docker-compose.yml  down
# docker exec -it <container_name_or_id> /bin/bash
# yes | docker system prune --all
